# Generated by Django 3.1.7 on 2021-04-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('precio', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
                ('dormitorios', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('direccion', models.TextField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
