# Generated by Django 3.1.7 on 2021-04-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedaditem',
            name='banos',
        ),
        migrations.RemoveField(
            model_name='propiedaditem',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='propiedaditem',
            name='dormitorios',
        ),
        migrations.RemoveField(
            model_name='propiedaditem',
            name='metros_cuadrados',
        ),
        migrations.RemoveField(
            model_name='propiedaditem',
            name='precio',
        ),
    ]
