# Generated by Django 3.1.7 on 2021-04-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210428_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropiedadItem',
            new_name='NewsItem',
        ),
    ]
