# Generated by Django 3.1.7 on 2021-05-06 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210428_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
