TIPO_DE_PROPIEDAD = [
    'arriendo',
    'venta',
]

COMUNA = [
    (1, 'Cerrillos'),
    (2, 'Cerro Navia'),
    (3, 'Conchalí'),
    (4, 'El Bosque'),
    (5, 'Estación Central'),
    (6, 'Huechuraba'),
    (7, 'Independencia'),
    (8, 'La Cisterna'),
    (9, 'La Florida'),
    (10, 'La Granja'),
    (11, 'La Pintana'),
    (12, 'La Reina'),
    (13, 'Las Condes'),
    (14, 'Lo Espejo'),
    (15, 'Lo Barnechea'),
    (16, 'Lo Prado'),
    (17, 'Macul'),
    (18, 'Maipú'),
    (19, 'Ñuñoa'),
    (20, 'Pedro Aguirre Cerda'),
    (21, 'Peñalolen'),
    (22, 'Providencia'),
    (23, 'Pudahuel'),
    (24, 'Quilicura'),
    (25, 'Quinta Normal'),
    (26, 'Recoleta'),
    (27, 'Renca'),
    (28, 'Santiago'),
    (29, 'San Joaquín'),
    (30, 'San Miguel'),
    (31, 'San Ramon'),
    (32, 'Vitacura'),
]